language: node_js
node_js:
deploy:
  provider: gae
  keyfile: app-engine-service-account.json
  project: scvo-net
  on: dev-next
before_install:
- openssl aes-256-cbc -K $encrypted_9025fc4e977a_key -iv $encrypted_9025fc4e977a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- ls
- ls ./src
