service: scvo-frontend-dev
env: flexible
runtime: nodejs
api_version: '1.0'
threadsafe: true

manual_scaling:
  instances: 2

network:
  name: default

resources:
  cpu: 1
  memory_gb: 1.75
  disk_size_gb: 10

health_check:
  enable_health_check: False
